package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mybean.data.*;

public final class showLoginMess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.Vector _jspx_dependants;

  public java.util.List getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=GB2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n");
      mybean.data.Login login = null;
      synchronized (session) {
        login = (mybean.data.Login) _jspx_page_context.getAttribute("login", PageContext.SESSION_SCOPE);
        if (login == null){
          throw new java.lang.InstantiationException("bean login not found within scope");
        }
      }
      out.write("\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n<title>星星旅行社</title>\r\n<style type=\"text/css\">\r\n  <!--\r\n    .style1 {color: #71AD23}\r\n    .style2 {color: #71AD23; font-size: 14px; }\r\n    .style3 {color: #FF6666}\r\n    a:link {\r\n    color: #FF6699;\r\n    }\r\n    .style4 {color: #71AD23; font-size: 12px; }\r\n    .style6 {color: #FF6666; font-size: 12px; }\r\n    .style7 {font-size: 12px}\r\n    .style8 {color: #FFFFFF}\r\n    .style9 {font-size: 12px; color: #FFFFFF; }\r\n  -->\r\n</style>\r\n</head>\r\n<body>\r\n<table width=\"756\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"F0F7FF\">\r\n  <!--DWLayoutTable-->\r\n  <tr>\r\n    <td colspan=\"3\" align=\"center\">\r\n      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n    </td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"222\" height=\"600\" valign=\"top\">\r\n      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n        <!--DWLayoutTable-->\r\n        <tr>\r\n          <td width=\"221\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td height=\"525\" valign=\"top\">\r\n                  <table width=\"219\" height=\"539\" border=\"0\" cellspacing=\"0\">\r\n                    <tr>\r\n                      <td height=\"23\" bgcolor=\"#D5FFB9\">                        　\r\n                        <img src=\"images/tits.gif\" width=\"12\" height=\"12\">\r\n                        &nbsp;&nbsp;\r\n                        <span class=\"style3\">会员登录</span>\r\n                      </td>\r\n                    </tr>\r\n                    <tr>\r\n                      <td height=\"40\" align=\"center\" background=\"images/bj4.gif\">\r\n                        <br>\r\n                        <span class=\"style8\">\r\n                        ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Login)_jspx_page_context.findAttribute("login")).getBackNews())));
      out.write("\r\n                      </span> </td>\r\n                    </tr>\r\n                    <tr>\r\n                      <td height=\"96\" align=\"center\" valign=\"middle\" background=\"images/1.jpg\">\r\n                        <br>\r\n                        <span class=\"style8\">\r\n\t\t\t\t\t\t");
 if(login.getSuccess()==true)
			  {
			  
      out.write(" 登录会员名称:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Login)_jspx_page_context.findAttribute("login")).getUser_name())));
      out.write("\r\n\t\t\t  ");
 }
			  else
			  {
			  
      out.write(" 登录会员名称:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Login)_jspx_page_context.findAttribute("login")).getUser_name())));
      out.write("\r\n\t\t\t     登录会员密码:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Login)_jspx_page_context.findAttribute("login")).getUser_key())));
      out.write("\r\n\t\t\t\t ");
 }
				 
      out.write(" </span>\r\n                      </td>\r\n                    </tr>\r\n                    <tr>\r\n                      <td height=\"380\">\r\n                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left_1.jsp", out, false);
      out.write("\r\n                      </td>\r\n                    </tr>\r\n                  </table>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"30\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"210\" height=\"30\" background=\"image/dbj.jpg\">\r\n                  <span class=\"style1\"> 　 <img src=\"images/003.gif\" width=\"16\" height=\"16\">　热点线路　　　<img src=\"images/13571911.gif\" width=\"36\" height=\"17\"></span>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"177\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"210\" height=\"187\">\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n");
      out.write("      </table>\r\n    </td>\r\n    <td width=\"379\" rowspan=\"2\" valign=\"top\">\r\n      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n        <!--DWLayoutTable-->\r\n        <tr>\r\n          <td width=\"385\" height=\"240\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"381\" height=\"30\" valign=\"top\">\r\n                  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                    <!--DWLayoutTable-->\r\n                    <tr>\r\n                      <td width=\"385\" height=\"30\">\r\n                        <MARQUEE scrollAmount=1 scrollDelay=3 class=\"style3\" onmouseover=this.stop() onmouseout=this.start()>大家好，欢迎访问星星旅行社！</MARQUEE>\r\n                      </td>\r\n                    </tr>\r\n                  </table>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"25\" valign=\"top\">\r\n                  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                    <!--DWLayoutTable-->\r\n                    <tr>\r\n                      <td width=\"25\" height=\"25\" valign=\"top\">\r\n                        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                          <!--DWLayoutTable-->\r\n                          <tr>\r\n                            <td width=\"47\" height=\"25\">\r\n                              <img src=\"images/004.gif\" width=\"16\" height=\"16\">\r\n                            </td>\r\n                          </tr>\r\n                        </table>\r\n                      </td>\r\n                      <td width=\"306\" background=\"images/dbj.jpg\">\r\n                        <div align=\"center\" class=\"style2\">公告栏</div>\r\n                      </td>\r\n                      <td width=\"42\" valign=\"top\">\r\n                        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                          <!--DWLayoutTable-->\r\n                          <tr>\r\n                            <td width=\"42\" height=\"25\" valign=\"top\" background=\"images/dbj.jpg\">\r\n");
      out.write("                              <img src=\"images/13571911.gif\" width=\"36\" height=\"17\">\r\n                            </td>\r\n                          </tr>\r\n                        </table>\r\n                      </td>\r\n                      <td width=\"12\" valign=\"top\">\r\n                        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                          <!--DWLayoutTable-->\r\n                          <tr>\r\n                            <td width=\"12\" height=\"25\">\r\n                              <img src=\"images/youshangjiao.gif\" width=\"12\" height=\"25\">\r\n                            </td>\r\n                          </tr>\r\n                        </table>\r\n                      </td>\r\n                    </tr>\r\n                  </table>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"160\" valign=\"top\">\r\n                  <table width=\"97%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                    <!--DWLayoutTable-->\r\n                    <tr>\r\n");
      out.write("                      <td width=\"9\" height=\"160\" valign=\"top\">\r\n                        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                          <!--DWLayoutTable-->\r\n                          <tr>\r\n                            <td width=\"10\" height=\"160\">&nbsp;</td>\r\n                          </tr>\r\n                        </table>\r\n                      </td>\r\n                      <td width=\"360\" bgcolor=\"#FFFFFF\">\r\n\r\n                      </td>\r\n                    </tr>\r\n                  </table>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"25\" valign=\"top\">\r\n                  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                    <!--DWLayoutTable-->\r\n                    <tr>\r\n                      <td width=\"25\" height=\"25\" valign=\"top\">\r\n                        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                          <!--DWLayoutTable-->\r\n                          <tr>\r\n");
      out.write("                            <td width=\"25\" height=\"25\" valign=\"top\">\r\n                              <img src=\"images/zuojiao.gif\" width=\"25\" height=\"20\">\r\n                            </td>\r\n                          </tr>\r\n                        </table>\r\n                      </td>\r\n                      <td width=\"347\" background=\"images/xbkbg.gif\">&nbsp;</td>\r\n                      <td width=\"10\" valign=\"top\">\r\n                        <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                          <!--DWLayoutTable-->\r\n                          <tr>\r\n                            <td width=\"12\" height=\"25\">&nbsp;</td>\r\n                          </tr>\r\n                        </table>\r\n                      </td>\r\n                    </tr>\r\n                  </table>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"30\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"385\" height=\"30\" background=\"images/dbj.jpg\">\r\n                  <span class=\"style2\">　<img src=\"images/150.gif\" width=\"17\" height=\"15\">　　　　　　　　旅游线路查询</span>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"13\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"385\" height=\"13\" valign=\"middle\">\r\n                  <form name=\"form2\" method=\"post\" action=\"show_line.jsp\">\r\n                  <table width=\"100%\" border=\"0\" cellspacing=\"0\">\r\n                    <tr>\r\n                      <td width=\"38%\">\r\n                        <div align=\"center\" class=\"style1\">旅游线路名称:</div>\r\n                      </td>\r\n                      <td width=\"47%\">\r\n                        <input type=\"text\" name=\"tour_line_name\">\r\n                      </td>\r\n");
      out.write("                      <td width=\"15%\">\r\n                        <input type=\"submit\" name=\"Submit3\" value=\"查询\">\r\n                      </td>\r\n                    </tr>\r\n                  </table>\r\n                  </form>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"23\" valign=\"top\"><!--DWLayoutEmptyCell-->&nbsp;\r\n\r\n\r\n          </td>\r\n        </tr>\r\n      </table>\r\n      <table width=\"379\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n        <tr>\r\n          <td width=\"379\" height=\"163\">\r\n            <table width=\"377\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <tr>\r\n                <td width=\"377\" height=\"26\" background=\"images/dbj.jpg\">                  　\r\n                  <img src=\"images/icon.gif\" width=\"21\" height=\"21\">\r\n                  　\r\n                  <span class=\"style2\">签证办理</span>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"151\">\r\n                  <table width=\"378\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                    <tr>\r\n                      <td width=\"126\" height=\"79\">\r\n                        <img src=\"images/france.png\" width=\"125\" height=\"80\">\r\n                      </td>\r\n                      <td width=\"126\">\r\n                        <img src=\"images/england.png\" width=\"125\" height=\"80\">\r\n                      </td>\r\n                      <td width=\"126\">\r\n                        <img src=\"images/usa.png\" width=\"125\" height=\"80\">\r\n                      </td>\r\n                    </tr>\r\n                    <tr class=\"style1\">\r\n                      <td height=\"25\" align=\"center\">\r\n                        <a href=\"#\" class=\"style4\">法国旅游签证</a>\r\n                      </td>\r\n                      <td align=\"center\" class=\"style4\">\r\n                        <a href=\"#\">英国旅游签证</a>\r\n                      </td>\r\n                      <td align=\"center\" class=\"style4\">\r\n                        <a href=\"#\">美国旅游签证</a>\r\n                      </td>\r\n                    </tr>\r\n                    <tr class=\"style6\">\r\n");
      out.write("                      <td height=\"28\" align=\"center\">\r\n                        <span class=\"style6\">￥1599</span>\r\n                      </td>\r\n                      <td align=\"center\">\r\n                        <span class=\"style3\">￥1500</span>\r\n                      </td>\r\n                      <td align=\"center\">\r\n                        <span class=\"style3\">￥1400</span>\r\n                      </td>\r\n                    </tr>\r\n                  </table>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"176\">\r\n            <table width=\"379\" height=\"174\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <tr background=\"images/dbj.jpg\">\r\n                <td height=\"30\" colspan=\"5\">                  　\r\n                  <img src=\"images/icon_03.gif\" width=\"25\" height=\"14\">\r\n                  　\r\n                  <span class=\"style2\">特价机票</span>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td width=\"86\">&nbsp;</td>\r\n");
      out.write("                <td width=\"93\" align=\"center\" class=\"style4\">出发地/目的地</td>\r\n                <td width=\"54\" align=\"center\" class=\"style4\">类型</td>\r\n                <td width=\"80\" align=\"center\" class=\"style4\">出发日期</td>\r\n                <td width=\"66\" align=\"center\" class=\"style4\">起价</td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"45\" align=\"center\">\r\n                  <img src=\"images/xg.jpg\" width=\"74\" height=\"45\">\r\n                </td>\r\n                <td rowspan=\"2\" align=\"center\" class=\"style6\">\r\n                  <a href=\"#\">北京-香港</a>\r\n                </td>\r\n                <td rowspan=\"2\" align=\"center\" class=\"style6\">往返</td>\r\n                <td rowspan=\"2\" align=\"center\" class=\"style6\">2009-04-21</td>\r\n                <td rowspan=\"2\" align=\"center\" class=\"style6\">￥1500</td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"13\" align=\"center\">\r\n                  <span class=\"style7\">香港</span>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"45\" align=\"center\" valign=\"middle\">\r\n");
      out.write("                  <img src=\"images/oz.jpg\" width=\"74\" height=\"45\">\r\n                </td>\r\n                <td colspan=\"4\" rowspan=\"2\">                  　\r\n                  <span class=\"style6\">此航线暂无特价机票</span>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"13\" align=\"center\">\r\n                  <span class=\"style7\">欧洲</span>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"59\" valign=\"top\">\r\n            <table width=\"379\" height=\"65\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <tr>\r\n                <td height=\"28\" background=\"images/dbj.jpg\">                  　\r\n                  <img src=\"images/001.gif\" width=\"16\" height=\"15\">\r\n                  　\r\n                  <span class=\"style2\">友情链接</span>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"37\" align=\"center\">\r\n                  <span class=\"style4\"><a href=\"http://www.169trip.com/\">云南旅游网</a>　<a href=\"http://www.utourworld.com/\">众信旅游网</a>　<a href=\"http://www.cn5518.cn/\">携程旅游网</a>　<a href=\"http://www.kuxun.cn/\">酷讯旅游网</a>　<a href=\"www.baidu.com\">百度</a></span>\r\n");
      out.write("                  　\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n      </table>\r\n    </td>\r\n    <td width=\"155\" valign=\"top\">\r\n      <br>\r\n      <table width=\"97%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n        <!--DWLayoutTable-->\r\n        <tr>\r\n          <td width=\"155\" height=\"120\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"155\" height=\"98\" valign=\"top\">\r\n                  <div align=\"center\">\r\n                    <img src=\"images/jiuzaigou.jpg\" width=\"155\" height=\"98\">\r\n                  </div>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"22\">\r\n                  <div align=\"center\">\r\n                    <a href=\"#\" class=\"style4\">九寨沟</a>\r\n                  </div>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n");
      out.write("          <td height=\"120\" valign=\"top\">\r\n            <table width=\"97%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"155\" height=\"98\" valign=\"top\">\r\n                  <div align=\"center\">\r\n                    <img src=\"images/bdlg.jpg\" width=\"155\" height=\"98\">\r\n                  </div>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"22\">\r\n                  <div align=\"center\">\r\n                    <a href=\"#\" class=\"style4\">布达拉宫</a>\r\n                  </div>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"120\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"165\" height=\"98\" valign=\"top\">\r\n                  <div align=\"center\">\r\n                    <img src=\"images/zhyn.jpg\" width=\"155\" height=\"98\">\r\n");
      out.write("                  </div>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"22\">\r\n                  <div align=\"center\">\r\n                    <a href=\"#\" class=\"style4\">珠海渔女像</a>\r\n                  </div>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"120\" valign=\"top\">\r\n            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n              <!--DWLayoutTable-->\r\n              <tr>\r\n                <td width=\"165\" height=\"98\" valign=\"top\">\r\n                  <div align=\"center\">\r\n                    <img src=\"images/lmgc.jpg\" width=\"155\" height=\"98\">\r\n                  </div>\r\n                </td>\r\n              </tr>\r\n              <tr>\r\n                <td height=\"22\">\r\n                  <div align=\"center\">\r\n                    <a href=\"#\" class=\"style4\">罗马广场</a>\r\n                  </div>\r\n                </td>\r\n              </tr>\r\n            </table>\r\n          </td>\r\n");
      out.write("        </tr>\r\n        <tr>\r\n          <td height=\"98\" valign=\"top\">\r\n            <div align=\"center\">\r\n              <img src=\"images/sbd.jpg\" width=\"155\" height=\"98\">\r\n            </div>\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"22\">\r\n            <div align=\"center\">\r\n              <a href=\"#\" class=\"style4\">塞班岛</a>\r\n            </div>\r\n          </td>\r\n        </tr>\r\n      </table>\r\n      <table width=\"155\" height=\"134\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n        <tr>\r\n          <td height=\"99\" valign=\"top\">\r\n            <img src=\"images/hs.jpg\" width=\"155\" height=\"98\">\r\n          </td>\r\n        </tr>\r\n        <tr>\r\n          <td height=\"23\" align=\"center\">\r\n            <a href=\"#\" class=\"style4\">黄山迎客松</a>\r\n          </td>\r\n        </tr>\r\n      </table>\r\n    </td>\r\n  </tr>\r\n  <tr>\r\n    <td height=\"2\">    </td>\r\n    <td>    </td>\r\n  </tr>\r\n</table>\r\n<table width=\"760\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n  <tr>\r\n    <td width=\"760\" height=\"27\" align=\"center\" bgcolor=\"#71AD23\">\r\n");
      out.write("      <span class=\"style9\">制作人：中华女子学院05级计算机系 梁倩倩</span>\r\n    </td>\r\n  </tr>\r\n</table>\r\n</body>\r\n</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
